### ISSUE TITLE
Feature: Creating groups via a collection on contacts

### ISSUE THREAD

**Issue by commitshappen** [commitshappen/DSCP-Partner-Portal-API#15]
**Bug, feature request, or proposal:**
Feature

**What is the expected behavior?**
An authenticated user should be able to CRUD a group with the following properties: 
* name
* description
* timestamps

These groups will also have a number of many-to-many relationships, including ones with contacts, notes, and links. The contacts have already been created, but notes and links have not. 

Notes should have the following attributes: 
* content
* user_id
* timestamps

And links should have the following attributes: 
* title
* destination
* timestamps

**What is the current behavior?**
n/a

**What are the steps to reproduce?**
n/a

**What is the use-case or motivation for changing an existing behavior?**
Requirements on the current design prototype and needs of the DSCP staff

**Is there anything else we should know?**
If you lift a kangaroo’s tail off the ground it can’t hop.

**Comment by freeranger** [comment]
@commitshappen I'll take a look at this - is "content" a text field or a string?

And you definitely want many to many relationships? 
* A Group has many Contacts, a Contact has many Groups (fair enough)
* A Group has many Notes, a Note has many Groups (seems odd?)
* A Group has many Links, a Link has many Groups (seems odd?)

Are there any other relationships to add?

**Comment by commitshappen** [comment]
@freeranger You're absolutely correct. The notes and links would be one-to-many. Sometime my brain no work properly ;)

Also, "content" would be a text field. So would description.
