### ISSUE TITLE
Expose Groups through the API

### ISSUE THREAD

**Issue by freeranger** [commitshappen/DSCP-Partner-Portal-API#17]
Suggest the following:
```
GET /api/groups - returns all groups in the database
GET /api/groups?search=XXXX - searches name (and description?), with name match ranking higher
GET /api/groups/:id - return a single group
GET /api/groups/:id/contacts - return the contacts for this group
GET /api/groups/:id/links - return the links for this group
GET /api/groups/:id/notes - return the notes for this group
POST /api/groups - create a group
PUT /api/groups/:id - update a group
DELETE /api/groups - delete a group 
```
We may also want to be able to navigate to groups from contacts, so we would add an end point
/api/contacts/:id/groups

For the GET operations, you might want to always return all related items (contacts, links, notes), or just return a link to get them.
An API very often includes a _links (or just "links") section to let you navigate to subsequent items, so you would have a group:
```
{
   name: "my group",
   description: "this is a lovely group",
   _links: {
      "self": { href: "/groups/1"},
      "contacts: { href: "/groups/1/contacts", title: "Contacts in this group" },
      "links: { href: "/groups/1/links"},
      "notes: { href: "/groups/1/notes",title: "Notes made by users in this group" }
   }
}
```
The "self" link is to get to the actual group - in this case, we return everything about the group so it doesn't add anything really, but when we list groups we don't necessarily want to list everything about them, so we might just provide a list of group summaries:
```
[
 {
   name: "my group",
   description: "this is a lovely group",
   _links: {
      "self": { href: "/groups/1"},
   },
 {
   name: "my other group",
   description: "this is a terrible group",
   _links: {
      "self": { href: "/groups/2"},
   },
etc
}]
```
You then follow the "self" link to the actual group to discover more about it, including where all the other links are.
It's art more than science figuring out how much/how little to return when listing resources.

It is also perfectly valid to mix and match these - you might decide you always want to return the "links" linked to the group when you get a single group because they are fairly small, but return _links to the contacts and the notes - or indeed you could go further and the group will return, say, contacts OR a link to contacts, depending on how many there are - ditto notes and links.  In this scenario you set a limit - lets say less than 5 links and you return them all, other wise you return a _link to get them.

**Comment by freeranger** [comment]
@commitshappen Do group names have to be unique?  I am thinking yes.
Note that I have no validations applied other than presence: true - nothing about minimum lengths etc.

**Comment by commitshappen** [comment]
@freeranger Yes, please keep the group names unique. There's no need to have multiple groups of the same name.
