### ISSUE TITLE
Expose Links through the API

### ISSUE THREAD

**Issue by freeranger** [commitshappen/DSCP-Partner-Portal-API#19]
I don't think these have any validity as a resource in their own right - they belong to a groupso it seems to me they would be exposed via the groups endpoint:
```
GET /api/groups/:id/links - returns all links for that group
GET /api/groups/:id/links?search=XXXX - searches title (and destination?), with title match ranking higher
GET /api/groups/:id/links/:linkid - return a single link
POST /api/groups/:id/links - create a link for that group
PUT /api/groups/:id/links/:linkid - update a link
DELETE /api/groups/:id/links/:linkid - delete a link
```

You may want the ability to search for links across all groups?  Something to discuss later if we need it.

**Comment by commitshappen** [comment]
@freeranger Agreed. None of them are needed on their own. I also don't see any need for them to be searchable, now or any point in the future.

**Comment by freeranger** [comment]
cool, no probs

**Comment by commitshappen** [comment]
@freeranger I don't think we need to do unique tests for this. While I don't imagine they're will be links of the same name, having multiple links with the same name wouldn't be a problem.

**Comment by freeranger** [comment]
@commitshappen sure thing.  Do you want to validate as a url or validate length?

**Comment by commitshappen** [comment]
@freeranger I'd do a max length validation of 256. A valid url check would also be nice.
