### ISSUE TITLE
The README.md build status refers to my repo :)

### ISSUE THREAD

**Issue by freeranger** [commitshappen/DSCP-Partner-Portal-API#2]
The build status badge is for my fork of the repo and not for this repo itself.
This needs to change to the automatated build for this actual repo.
I used semaphoreci because it's quick and easy to set up and free for open source projects, but there are other solutions out there.
Having an automated build + test (and possibly deploy too, say to a heroku "dev" environment) is a very good thing indeed - it's just a question of which service you use :)

**Comment by commitshappen** [comment]
@freeranger A new automated build has been created on [Semaphore](https://semaphoreci.com/commitshappen/dscp-partner-portal-api) for this project. I'll be adding automatic deployment to Heroku shortly, which will run on the passing of the tests. 

Thanks for the update! :)

**Comment by commitshappen** [comment]
https://github.com/commitshappen/DSCP-Partner-Portal-API/commit/d47c6845e8050413735a1fdaf377828dac9dac73
