### ISSUE TITLE
Add "self" link to Contacts

### ISSUE THREAD

**Issue by freeranger** [commitshappen/DSCP-Partner-Portal-API#20]
When we retrieve a list of Contacts, we should return a reduced set of data, together with a "self" link to get to the individual contact with all it's details.

What fields do we want to return in the summary when you go to `/contacts`?

**Comment by commitshappen** [comment]
@freeranger We should only need first_name, last_name, email, business_name, and id when we are in list view. All other attributes would just be available then on the self view.

**Comment by freeranger** [comment]
@commitshappen - you don't really need id as you will have the self link which comes with the id...

**Comment by commitshappen** [comment]
@freeranger Sounds good.
